version: '3'
services:
  frontend:
    image:  d21daf4340874b5b2bf858de0b4267ed3a1b7d29925456d2c9fb3d7470489391
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: ./backend
    image: 8a834de4267532bba4be46b26b4db6e5e68fdb9c3be9ab3456875a1749c9f9ae
    ports:
      - "8120:8120"
    environment:
      - PORT = 8120
      - MONGO_URL = 'mongodb+srv://tententgc:tenten2546@os-project.s4cynb3.mongodb.net/?retryWrites=true&w=majority'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
