version: '3'
services:
  frontend:
    image:  d21daf4340874b5b2bf858de0b4267ed3a1b7d29925456d2c9fb3d7470489391
    ports:
      - "3000:3000"
    environment:
      - PORT = 3000
      - REACT_APP_BACKEND_URL = 'http://localhost:8120'
    depends_on:
      - backend
  backend:
    image: faadb50a2ca9b8f4f13e6ba45f80894540667152c9cda2b97d09a99423277aa7
    ports:
      - "8120:8120"
    environment:
      - PORT = 8120
      - MONGO_URL = 'mongodb+srv://tententgc:tenten2546@os-project.s4cynb3.mongodb.net/?retryWrites=true&w=majority'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
